<script setup lang="ts">
const route = useRoute()
const slug = Array.isArray(route.params.slug) ? route.params.slug.join('-') : String(route.params.slug || '')
type PageContent = { eyebrow:string; title:string; intro:string; image:string; imageAlt:string; sections:{title:string;text:string}[]; features:{icon:string;title:string;text:string}[]; faq:[string,string][] }
const freightPages:Record<string,PageContent> = {
  'fret-aerien': { eyebrow:'Rapide et suivi', title:'Fret aérien vers l’Afrique de l’Ouest', intro:'Une solution express au départ de la France pour vos colis légers, vêtements, bijoux et appareils électroniques.', image:'/fret-aerien-premium.png', imageAlt:'Remise d’un colis au terminal de fret aérien', sections:[{title:'Une expédition simple',text:'Indiquez la destination, la nature et le poids du colis. Nous confirmons le tarif, réceptionnons ou collectons votre envoi, puis vous tenons informé jusqu’à sa remise.'},{title:'Achats en ligne',text:'Faites livrer vos commandes à notre dépôt en France. Nous les réceptionnons avant de les réexpédier vers votre destination.'}], features:[{icon:'01',title:'Départ rapide',text:'Un mode de transport adapté aux envois urgents et peu volumineux.'},{icon:'02',title:'Tarif au poids',text:'Une estimation claire selon le poids, la destination et la nature du colis.'},{icon:'03',title:'Suivi humain',text:'Une équipe disponible pour vous informer à chaque étape.'}], faq:[['Quels colis envoyer par avion ?','Les vêtements, petits équipements, cadeaux et autres marchandises autorisées et peu volumineuses.'],['Comment connaître mon tarif ?','Le prix dépend du poids, de la destination et du contenu. Demandez un devis pour obtenir un montant confirmé.']] },
  'fret-maritime': { eyebrow:'Économique et adapté aux volumes', title:'Fret maritime vers l’Afrique de l’Ouest', intro:'La solution pensée pour les cartons, barriques, effets personnels, meubles et envois volumineux.', image:'/fret-maritime-premium.png', imageAlt:'Famille préparant un envoi maritime', sections:[{title:'Préparez à votre rythme',text:'Nous pouvons vous fournir un emballage adapté. Chaque colis doit porter les coordonnées de l’expéditeur, du destinataire et la destination complète.'},{title:'Collecte sur rendez-vous',text:'Une fois le colis prêt, planifiez un enlèvement en Île-de-France. Hors Île-de-France, nous étudions avec vous la meilleure solution.'}], features:[{icon:'01',title:'Grands volumes',text:'Cartons, barriques, mobilier et effets personnels trouvent leur place.'},{icon:'02',title:'Budget maîtrisé',text:'Une tarification adaptée au carton ou au volume selon votre besoin.'},{icon:'03',title:'Transport encadré',text:'Votre expédition est suivie du dépôt jusqu’à la remise locale.'}], faq:[['Quel délai prévoir ?','Le maritime prend plusieurs semaines. Le délai précis dépend du prochain départ et de la destination.'],['Comment étiqueter mon colis ?','Indiquez clairement les noms et téléphones de l’expéditeur et du destinataire, ainsi que la ville et le pays.']] },
  'envois-colis-paris-lome': { eyebrow:'France → Togo', title:'Envoi de colis de Paris vers Lomé', intro:'Pour la famille, la maison ou un projet : nous organisons votre envoi depuis Paris et l’Île-de-France jusqu’à Lomé.', image:'/lome-premium.png', imageAlt:'Réception d’un colis à Lomé au Togo', sections:[{title:'Aérien ou maritime',text:'Choisissez la rapidité de l’aérien pour un colis léger, ou l’économie du maritime pour des cartons, barriques et effets personnels.'},{title:'Collecte en Île-de-France',text:'Nous récupérons votre colis à domicile ou à l’adresse convenue, sur rendez-vous.'}], features:[{icon:'01',title:'Contactez-nous',text:'Décrivez le colis, son poids ou son volume et votre adresse de collecte.'},{icon:'02',title:'Choisissez le transport',text:'Nous vous aidons à arbitrer entre délai, volume et budget.'},{icon:'03',title:'Suivez le colis',text:'Vous restez informé jusqu’à la réception à Lomé.'}], faq:[['Proposez-vous l’enlèvement ?','Oui, sur rendez-vous en Île-de-France.'],['Puis-je envoyer un achat en ligne ?','Oui, vos commandes peuvent être réceptionnées en France puis réexpédiées vers Lomé.']] },
  'envois-colis-paris-cotonou': { eyebrow:'France → Bénin', title:'Envoi de colis de Paris vers Cotonou', intro:'Nous accompagnons vos envois de colis, marchandises autorisées et effets personnels depuis la région parisienne vers Cotonou.', image:'/cotonou-premium.png', imageAlt:'Réception d’un colis à Cotonou au Bénin', sections:[{title:'Deux solutions d’envoi',text:'L’aérien convient aux petits colis urgents. Le maritime est idéal pour les volumes importants et les envois familiaux.'},{title:'De porte à destination',text:'Nous organisons la collecte en Île-de-France et vous accompagnons pendant l’acheminement jusqu’à Cotonou.'}], features:[{icon:'01',title:'Devis transparent',text:'Le tarif est confirmé selon les caractéristiques réelles de votre envoi.'},{icon:'02',title:'Enlèvement planifié',text:'Choisissez avec notre équipe un créneau de collecte adapté.'},{icon:'03',title:'Relais local',text:'Un accompagnement jusqu’à la remise de votre colis à Cotonou.'}], faq:[['Comment choisir entre avion et bateau ?','Choisissez l’aérien pour la vitesse et le maritime pour un meilleur coût sur les gros volumes.'],['Quels renseignements fournir ?','La destination, le contenu, les dimensions, le poids approximatif et l’adresse de collecte.']] }
}
const fallback:PageContent = { eyebrow:'WefretAfrica', title:'Demander un devis', intro:'Décrivez votre envoi et notre équipe vous orientera vers la solution la plus adaptée.', image:'/hero.jpg', imageAlt:'Transport de colis vers l’Afrique', sections:[{title:'Préparez votre demande',text:'Indiquez la destination, le contenu, le poids ou les dimensions du colis et votre commune de collecte.'}], features:[{icon:'01',title:'Votre besoin',text:'Partagez les caractéristiques de l’envoi.'},{icon:'02',title:'Notre proposition',text:'Recevez une solution adaptée et un tarif confirmé.'},{icon:'03',title:'Votre départ',text:'Planifiez le dépôt ou l’enlèvement.'}], faq:[] }
const page = freightPages[slug] || fallback
useSeoMeta({title:`${page.title} | WefretAfrica`,description:page.intro,ogTitle:page.title,ogDescription:page.intro,ogType:'website'})
useHead({link:[{rel:'canonical',href:`https://www.wefretafrica.com/${slug}`}]})
</script>
<template><main>
  <div class="topbar"><span>France → Togo & Bénin</span><span class="topbar-contact"><a href="tel:+33676492528">☎ 06 76 49 25 28</a><a href="https://www.google.com/maps/search/?api=1&query=15+Rue+des+Écoles+95500+Le+Thillay" target="_blank" rel="noopener">⌖ Le Thillay</a></span></div>
  <header><NuxtLink class="brand" to="/"><img src="/logo.png" alt="Logo WefretAfrica"><b>WeFret<span>Africa</span></b></NuxtLink><nav><NuxtLink to="/#services">Nos services</NuxtLink><NuxtLink to="/#destinations">Destinations</NuxtLink><NuxtLink to="/#process">Comment ça marche</NuxtLink><NuxtLink to="/blog">Blog</NuxtLink></nav><NuxtLink class="btn small" to="/devis-en-ligne">Estimer mon envoi</NuxtLink></header>
  <section class="page-hero"><div><p class="eyebrow">{{page.eyebrow}}</p><h1>{{page.title}}</h1><p>{{page.intro}}</p><div class="actions"><NuxtLink class="btn" to="/devis-en-ligne">Obtenir un devis</NuxtLink><a class="btn ghost" href="#solutions">Voir la solution</a></div></div><img :src="page.image" :alt="page.imageAlt"></section>
  <section id="solutions" class="section page-features"><div class="heading"><div><p class="kicker">Une prise en charge claire</p><h2>Votre envoi, <em>étape par étape</em></h2></div><p>De la préparation à la réception, vous savez toujours où en est votre colis.</p></div><div class="cards"><article v-for="feature in page.features" :key="feature.title"><i>{{feature.icon}}</i><h3>{{feature.title}}</h3><p>{{feature.text}}</p></article></div></section>
  <section v-if="slug==='fret-aerien'" class="transport-notice"><span>48 h</span><div><p class="kicker">Avant chaque départ aérien</p><h2>Déposez votre colis <em>48 heures avant</em></h2><p>Ce délai nous permet de contrôler, enregistrer et préparer votre expédition. Le délai indicatif de livraison aérienne est ensuite d’une semaine.</p></div></section>
  <section v-if="slug==='fret-maritime'" class="transport-notice sea-notice"><span>10 €</span><div><p class="kicker">Carton et collecte</p><h2>Nous vous aidons à <em>préparer le colis</em></h2><p>Le carton vide coûte 10 €. En Île-de-France, nous vous l’apportons gratuitement et revenons récupérer le colis dès qu’il est rempli.</p></div></section>
  <section v-if="slug==='envois-colis-paris-lome'" class="transport-notice"><span>1 mois</span><div><p class="kicker">Délai maritime indicatif</p><h2>Votre envoi vers <em>le Togo</em></h2><p>Prévoyez environ un mois d’acheminement maritime à compter du départ. En aérien, le délai indicatif est d’une semaine.</p></div></section>
  <section v-if="slug==='envois-colis-paris-lome'" class="pickup-location"><div class="pickup-pin">⌖</div><div><p class="kicker">Retrait du fret maritime à Lomé</p><h2>Récupérez votre colis maritime dans <em>notre dépôt</em></h2><p>Pour les envois par bateau uniquement, les colis sont à récupérer dans notre dépôt situé vers <strong>Adéwui, à côté du bar 3/4</strong>. Notre équipe vous informe dès que votre colis est disponible au retrait.</p><NuxtLink class="text-link" to="/devis-en-ligne?destination=Togo&transport=Maritime">Organiser mon envoi maritime vers Lomé →</NuxtLink></div></section>
  <section v-if="slug==='envois-colis-paris-cotonou'" class="transport-notice"><span>1,5 mois</span><div><p class="kicker">Délai maritime indicatif</p><h2>Votre envoi vers <em>le Bénin</em></h2><p>Prévoyez environ un mois et demi d’acheminement maritime à compter du départ. En aérien, le délai indicatif est d’une semaine.</p></div></section>
  <DepartureSchedule v-if="slug==='fret-maritime'" />
  <section class="content-split"><img :src="page.image" :alt="page.imageAlt"><div><p class="kicker">La solution WefretAfrica</p><article v-for="section in page.sections" :key="section.title"><h2>{{section.title}}</h2><p>{{section.text}}</p></article><NuxtLink class="text-link" to="/devis-en-ligne">Parler de mon envoi →</NuxtLink></div></section>
  <section v-if="page.faq.length" class="section faq page-faq"><div><p class="kicker">Questions fréquentes</p><h2>Avant de <em>vous lancer</em></h2></div><div><details v-for="(item,index) in page.faq" :key="item[0]" :open="index===0"><summary>{{item[0]}} <span>+</span></summary><p>{{item[1]}}</p></details></div></section>
  <section class="cta"><h2>Prêt à organiser votre <em>prochain envoi ?</em></h2><NuxtLink class="btn white" to="/devis-en-ligne">Demander mon devis →</NuxtLink></section>
  <footer><div class="brand"><img src="/logo.png" alt=""><b>WeFret<span>Africa</span></b></div><p>Votre partenaire pour l’envoi de colis entre la France et l’Afrique de l’Ouest.</p><div class="footer-links"><NuxtLink to="/fret-aerien">Fret aérien</NuxtLink><NuxtLink to="/fret-maritime">Fret maritime</NuxtLink><NuxtLink to="/blog">Blog</NuxtLink></div><small>© 2026 WefretAfrica. Tous droits réservés.</small></footer>
</main></template>
