<script setup lang="ts">
useSeoMeta({title:'Envoi de colis France–Togo et Bénin | WefretAfrica',description:'Fret aérien et maritime depuis la France vers le Togo et le Bénin, ainsi que d’autres pays d’Afrique de l’Ouest.',ogTitle:'WefretAfrica — France, Togo et Bénin',ogDescription:'Envoyez vos colis vers le Togo, le Bénin et l’Afrique de l’Ouest.',ogType:'website',ogLocale:'fr_FR',ogUrl:'https://www.wefretafrica.com/',ogImage:'https://www.wefretafrica.com/hero-premium.png',ogImageAlt:'Envoi de colis entre la France, le Togo et le Bénin avec WefretAfrica',ogImageWidth:1672,ogImageHeight:941,twitterCard:'summary_large_image',twitterImage:'https://www.wefretafrica.com/hero-premium.png'})
const services=[['✈','Fret aérien','Une solution rapide pour vos colis urgents vers Lomé, Cotonou et nos autres destinations.','/fret-aerien'],['▰','Fret maritime','Expédiez vos colis et effets personnels à prix maîtrisé, avec un suivi clair à chaque étape.','/fret-maritime'],['⌂','Enlèvement à domicile','Nous récupérons vos colis chez vous en Île-de-France, sur rendez-vous.','/devis-en-ligne']]
const faqs=[['Quels types de colis puis-je envoyer ?','Effets personnels, vêtements, électroménager et marchandises autorisées.'],['Comment suivre mon colis ?','Un numéro de suivi vous permet de consulter l’avancement de votre envoi.'],['Fret aérien ou maritime : que choisir ?','L’aérien privilégie la rapidité. Le maritime est plus économique pour les volumes importants.']]
const structuredData={'@context':'https://schema.org','@graph':[{'@type':'LocalBusiness','@id':'https://www.wefretafrica.com/#business',name:'WefretAfrica',url:'https://www.wefretafrica.com/',image:'https://www.wefretafrica.com/hero-premium.png',logo:'https://www.wefretafrica.com/logo.png',telephone:'+33676492528',description:'Service de fret aérien et maritime depuis la France vers le Togo, le Bénin et l’Afrique de l’Ouest.',address:{'@type':'PostalAddress',streetAddress:'15 Rue des Écoles',postalCode:'95500',addressLocality:'Le Thillay',addressCountry:'FR'},areaServed:['Île-de-France','Togo','Bénin','Afrique de l’Ouest']},{'@type':'FAQPage',mainEntity:faqs.map(([name,text])=>({'@type':'Question',name,acceptedAnswer:{'@type':'Answer',text}}))}]}
useHead({link:[{rel:'canonical',href:'https://www.wefretafrica.com/'}],script:[{type:'application/ld+json',innerHTML:JSON.stringify(structuredData)}]})
</script>
<template>
<main>
  <div class="topbar"><span>France → Togo & Bénin</span><span class="topbar-contact"><a href="tel:+33676492528">France : 06 76 49 25 28</a><a href="tel:+22892000869">Togo : +228 92 00 08 69</a></span></div>
  <header><NuxtLink class="brand" to="/"><img src="/logo.png" alt="Logo WefretAfrica"><b>WeFret<span>Africa</span></b></NuxtLink><nav><a href="#infos-pratiques">Tarifs & délais</a><a href="#calculateur">Calculateur</a><a href="#destinations">Destinations</a><a href="#departs">Prochains départs</a><NuxtLink to="/blog">Blog</NuxtLink></nav><NuxtLink class="btn small" to="/devis-en-ligne">Demander un devis</NuxtLink></header>
  <section class="hero"><div class="hero-content"><p class="eyebrow">France → Togo & Bénin</p><h1>Envoyez au Togo et au Bénin, <em>sans complication.</em></h1><p>WefretAfrica organise vos envois par fret aérien dès 12 €/kg ou maritime dès 600 €/m³. Nous vous accompagnons de la préparation du colis jusqu’à sa remise à destination, avec enlèvement sur rendez-vous en Île-de-France. Les envois vers d’autres pays d’Afrique de l’Ouest sont étudiés sur devis.</p><div class="actions"><a class="btn" href="#calculateur">Calculer mon tarif</a><NuxtLink class="btn ghost" to="/devis-en-ligne">Demander un devis</NuxtLink></div><div class="trust">✓ Tarifs immédiats　 ✓ Délais annoncés　 ✓ Accompagnement humain</div></div></section>
  <section id="infos-pratiques" class="proof quick-proof"><article><small>✈ Aérien Togo</small><strong>12 €/kg</strong><span>1 semaine · dépôt 48 h avant</span></article><article><small>✈ Aérien Bénin</small><strong>15 €/kg</strong><span>1 semaine · dépôt 48 h avant</span></article><article><small>▰ Maritime Togo</small><strong>600 €/m³</strong><span>Environ 1 mois</span></article><article><small>▰ Maritime Bénin</small><strong>800 €/m³</strong><span>Environ 1 mois et demi</span></article></section>
  <section class="essential-banner"><div><b>Carton vide : 10 €</b><span>Livré gratuitement en Île-de-France, puis récupéré une fois rempli.</span></div><div><b>Maritime à Lomé</b><span>Retrait au dépôt vers Adéwui, à côté du bar 3/4.</span></div><a href="#departs">Voir les prochains départs →</a></section>
  <section id="tarifs-2026" class="section pricing-section"><div class="heading"><div><p class="kicker">Grille tarifaire 2026</p><h2>Des tarifs clairs, <em>selon votre besoin</em></h2></div><p>Transport maritime France → Afrique de l’Ouest. Les tarifs sont indicatifs et confirmés après vérification du volume et de la nature des marchandises.</p></div><div class="pricing-grid"><article class="pricing-card pricing-card-main"><div class="pricing-card-head"><span>01</span><h3>Tarif standard</h3><small>Avec collecte à domicile</small></div><div class="pricing-table"><div class="pricing-row pricing-labels"><b>Destination</b><b>m³</b><b>Grand carton</b><b>Petit carton</b><b>Délai</b></div><div class="pricing-row"><strong>🇹🇬 Lomé</strong><b>500 €</b><span>100 €</span><span>60 €</span><small>25–30 j</small></div><div class="pricing-row"><strong>🇨🇮 Abidjan</strong><b>600 €</b><span>120 €</span><span>70 €</span><small>30–35 j</small></div><div class="pricing-row"><strong>🇧🇯 Cotonou</strong><b>750 €</b><span>150 €</span><span>90 €</span><small>35–45 j</small></div></div></article><article class="pricing-card pricing-card-depot"><div class="pricing-card-head"><span>02</span><h3>Tarif dépôt</h3><small>Colis déjà emballés et prêts à expédier</small></div><div class="pricing-table"><div class="pricing-row pricing-labels"><b>Destination</b><b>m³</b><b>Grand carton</b><b>Petit carton</b><b></b></div><div class="pricing-row"><strong>🇹🇬 Lomé</strong><b>500 €</b><span>90 €</span><span>55 €</span><small></small></div><div class="pricing-row"><strong>🇨🇮 Abidjan</strong><b>600 €</b><span>110 €</span><span>65 €</span><small></small></div><div class="pricing-row"><strong>🇧🇯 Cotonou</strong><b>750 €</b><span>140 €</span><span>85 €</span><small></small></div></div></article><article class="pricing-card pricing-card-aside"><div class="pricing-card-head"><span>+</span><h3>À la carte</h3><small>Compléments utiles</small></div><ul><li><b>Carton vide</b><strong>10 €</strong></li><li><b>Petit carton vide</b><strong>5 €</strong></li><li><b>Ruban adhésif professionnel</b><strong>3 €</strong></li><li><b>Conditionnement simple</b><strong>10 €</strong></li><li><b>Conditionnement renforcé</b><strong>15 à 25 €</strong></li></ul><NuxtLink class="text-link" to="/devis-en-ligne">Besoin d’un tarif professionnel ? →</NuxtLink></article></div><p class="pricing-note">Les tarifs dépôt s’appliquent uniquement aux colis déjà emballés. Les marchandises volumineuses, palettes, fûts, vins et champagnes sont traités sur devis ou selon la grille dédiée.</p></section>
  <section id="services" class="section"><div class="heading"><div><p class="kicker">Nos solutions</p><h2>Fret aérien et maritime <em>vers le Togo et le Bénin</em></h2></div><p>De la collecte en France à la remise à destination, nous simplifions toutes les étapes. Consultez aussi nos <NuxtLink class="text-link" to="/blog">guides pratiques pour préparer votre colis</NuxtLink>.</p></div><div class="cards"><article v-for="(s,i) in services" :key="s[1]"><small>0{{i+1}}</small><i>{{s[0]}}</i><h3>{{s[1]}}</h3><p>{{s[2]}}</p><NuxtLink :to="s[3]">En savoir plus →</NuxtLink></article></div></section>
  <section id="calculateur" class="calculator"><div><p class="kicker">Estimation express</p><h2>Combien coûte votre <em>expédition ?</em></h2><p>Obtenez une première estimation en quelques secondes. Le tarif final est confirmé après vérification du colis.</p><ul><li>✓ Sans engagement</li><li>✓ Résultat immédiat</li><li>✓ Devis personnalisé</li></ul></div><PriceCalculator/></section>
  <section id="destinations" class="section destinations"><div class="heading"><div><p class="kicker">Nos destinations</p><h2>Le Togo et le Bénin, <em>en priorité</em></h2></div><p>Des liaisons principales vers Lomé et Cotonou, avec d’autres destinations d’Afrique de l’Ouest sur demande.</p></div><div class="destination-grid"><NuxtLink to="/envois-colis-paris-lome"><img src="/lome-premium.png" alt="Envoi Paris Lomé"><div><span>Destination principale · Togo</span><h3>Paris → Lomé</h3></div></NuxtLink><NuxtLink to="/envois-colis-paris-cotonou"><img src="/cotonou-premium.png" alt="Envoi Paris Cotonou"><div><span>Destination principale · Bénin</span><h3>Paris → Cotonou</h3></div></NuxtLink><NuxtLink to="/devis-en-ligne?destination=Abidjan%20%2F%20Côte%20d’Ivoire"><img src="/fret-maritime-premium.png" alt="Envoi Paris Abidjan"><div><span>Côte d’Ivoire · sur demande</span><h3>Paris → Abidjan</h3></div></NuxtLink></div></section>
  <section class="service-facts"><article><span>✈</span><div><small>Fret aérien</small><h3>Livraison en 1 semaine</h3><p>Votre colis doit nous parvenir au plus tard 48 h avant le départ.</p></div></article><article><span>▰</span><div><small>Fret maritime</small><h3>Carton vide à 10 €</h3><p>En Île-de-France, nous apportons gratuitement le carton puis venons le récupérer une fois rempli.</p></div></article><article><span>⌛</span><div><small>Délais maritimes</small><h3>Togo : 1 mois</h3><p>Bénin : environ 1 mois et demi après le départ.</p></div></article></section>
  <DepartureSchedule />
  <section id="process" class="process"><img src="/fret-maritime-premium.png" alt="Cliente préparant un envoi"><div><p class="kicker">Comment ça marche ?</p><h2>Votre colis avance,<br><em>vous restez informé.</em></h2><ol><li><b>01</b><p><strong>Demandez votre devis</strong><br>Renseignez la destination et les caractéristiques du colis.</p></li><li><b>02</b><p><strong>Planifiez l’enlèvement</strong><br>Choisissez un créneau en Île-de-France.</p></li><li><b>03</b><p><strong>Suivez l’expédition</strong><br>Consultez chaque étape grâce à votre numéro de suivi.</p></li></ol></div></section>
  <section id="faq" class="section faq"><div><p class="kicker">Questions fréquentes</p><h2>Tout savoir avant <em>d’envoyer</em></h2></div><div><details v-for="(f,i) in faqs" :key="f[0]" :open="i===0"><summary>{{f[0]}} <span>+</span></summary><p>{{f[1]}}</p></details></div></section>
  <section class="cta"><h2>Votre colis mérite un trajet <em>bien accompagné.</em></h2><a class="btn white" href="#calculateur">Estimer mon envoi →</a></section>
  <footer><div class="footer-main"><div><div class="brand"><img src="/logo.png" alt=""><b>WeFret<span>Africa</span></b></div><p>Votre partenaire pour l’envoi de colis entre la France, le Togo, le Bénin et l’Afrique de l’Ouest.</p></div><div class="footer-contact"><b>Nous contacter</b><a href="tel:+33676492528">06 76 49 25 28</a><a href="https://www.google.com/maps/search/?api=1&query=15+Rue+des+Écoles+95500+Le+Thillay" target="_blank" rel="noopener">15 Rue des Écoles<br>95500 Le Thillay, France</a></div><div class="footer-contact"><b>Liens rapides</b><a href="#calculateur">Calculer un tarif</a><NuxtLink to="/devis-en-ligne">Demander un devis</NuxtLink><a href="#departs">Prochains départs</a></div></div><small>© 2026 WefretAfrica. Tous droits réservés.</small></footer>
  <NuxtLink class="mobile-quote" to="/devis-en-ligne">Demander un devis</NuxtLink>
</main>
</template>
